### ISSUE TITLE
Crash adding a Fragment that already exists

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#231]
Looks like a simple call to check if the Fragment already exists is needed.

Stacktrace:
```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: ManageFragment{11664155 #1 dialog}
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1323)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:675)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
[Crashlytics issue.](https://fabric.io/cohen-adairs-projects/android/apps/com.cohenadair.anglerslog/issues/5881a8560aeb16625b50586d?time=last-seven-days)

**Comment by cohenadair** [comment]
Irrelevent for 2.0.
