### ISSUE TITLE
IllegalArgumentException creating a bitmap

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#232]
```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
       at com.google.maps.api.android.lib6.impl.a.b(:com.google.android.gms.DynamiteModulesB:63)
       at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.DynamiteModulesB:1734)
       at java.lang.Thread.run(Thread.java:818)
```
[Crashlytics issue](https://fabric.io/cohen-adairs-projects/android/apps/com.cohenadair.anglerslog/issues/59319530be077a4dcc95cf10?time=last-seven-days)

**Comment by cohenadair** [comment]
Irrelevent for 2.0.
