### ISSUE TITLE
Crash loading web view on Android

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#929]
https://console.firebase.google.com/u/0/project/anglers-log/crashlytics/app/android:com.cohenadair.anglerslog/issues/359ad4bb2c51272a55288b977a8f3ef7?time=last-seven-days&types=crash&sessionEventKey=66CAB94F001E00016A05123FCAE69694_1985385162181993717
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cohenadair.anglerslog/io.flutter.plugins.urllauncher.WebViewActivity}: java.lang.SecurityException: com.cohenadair.anglerslog: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4018)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4168)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2630)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        
```

**Comment by cohenadair** [comment]
Closing to be handled by agent triage skill.
